### ISSUE TITLE
Issue with citation and how to cite in the caption of the figures

### ISSUE THREAD

**Issue by nimasouzandeh** [CloudyOverhead/Gabarit_LaTeX_INRS#6]
Hello,

I have a problem with this template for my PhD thesis, First of all, I don't know why it doesn't let me read from "IEEEtran.bst" and always keep showing references between () rather than []; however, I use "
![latex1](https://github.com/CloudyOverhead/Gabarit_LaTeX_INRS/assets/171836494/5233a765-c51c-4b4e-8b25-2093bccb1f4a)
\cite" instead of "\citep". 

Also, when i put the citation in the caption of figures, it goes wrong in the number of all figures, and i don't know how to fix it. However, when i take off the citation from the caption like this \caption{figure1}\cite{ref1}, it is ok but always this reference comes in the line below the caption, which is not professional. i want this reference to stay in the same line in the caption of the figure

**Comment by nimasouzandeh** [comment]
Also there is another issue how to fix the table caption from french to English, instead of tableau i wanna see table?

**Comment by CloudyOverhead** [comment]
Hi @nimasouzandeh!

Thank you for taking the time for reporting this issue and for using this LaTeX template!

> I have a problem with this template for my PhD thesis, First of all, I don't know why it doesn't let me read from "IEEEtran.bst" and always keep showing references between () rather than []; however, I use "\cite" instead of "\citep".

I encourage you to read [this answer](https://github.com/CloudyOverhead/Gabarit_LaTeX_INRS/issues/4#issuecomment-1351903323) I have given another student. The difference between `\cite` and `\citep` is not whether parentheses or bracktes are used, but whether _Author (Year)_ or _(Author, Year)_ is used.

> Also, when i put the citation in the caption of figures, it goes wrong in the number of all figures, and i don't know how to fix it. However, when i take off the citation from the caption like this \caption{figure1}\cite{ref1}, it is ok but always this reference comes in the line below the caption, which is not professional. i want this reference to stay in the same line in the caption of the figure

I would need some more details or a [minimal working example](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that) in order to help you to the best of my ability. However, let me mention that I am aware of some interference that can happen when using references in captions. Here is an example of how I have used figure environments in my own thesis:
```latex
\begin{figure}[h]
    \centering
    \includegraphics{...}
    \caption[Conversion des ondes]{Conversion des ondes \citep{Giro19}}
    \legend{Les ondes de compression créées par une source explosive sont converties à la rencontre d'une interface dans un milieu isotrope élastique. Les vitesses sismiques sont plus grandes dans le milieu inférieur. Les ondes coniques sont causées par des réfractions à angle critique.}
    \label{fig:conversion}
\end{figure}
```
As you can see, I have added the reference in the short title, and I have also an optional title (between brackets) which doesn,t include it which allows the title of contents to format more nicely. There's also a longer legend under the figure, as per the INRS's guidelines for captions. You may try copying this code snippet and replacing your own reference and image.

> Also there is another issue how to fix the table caption from french to English, instead of tableau i wanna see table?

You may delete or comment out line 550 of `theseINRS.cls` (`\newcommand{\tablenamedef}{Tableau}`). Make sure that your thesis still follows [institutional guidelines](https://sdis.inrs.ca/wp-content/uploads/files/INRSGuideST_2022_eng.pdf) after that.

Do not hesitate if I can give any more help!

Cheers! 🚀

**Comment by nimasouzandeh** [comment]
Thanks for you reply. Your trick how to cite on the caption of figure works perfectly. I just couldnt find in theseINRS.cls to delet that comment, is there any way i can send you my theseINRS.cls to check it out, it may you have some ideas about it. Thank you

**Comment by CloudyOverhead** [comment]
You may put an attached file in this thread, and I can look at it if you wish. Ctrl-F might just solve your issue, however.
